[tasks.test]
description = "Run tests"
env = { RUST_BACKTRACE = '1' }
run = ["cargo test --features monoio/iouring,monoio/macros,global"]

[tasks.dev]
description = "Run dev"
run = ["cargo watch -c -x build --features global"]

[tasks.license]
description = "Generate license headers"
run = ["cargo run --example license"]
